fix: rename the button 'Rerun' to 'Run' on the b2i page #1543
kubesphere/console pull request #1894
Opened 2021-05-13 09:19 UTC by TinaSprunt

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
rename the button 'Rerun' to 'Run' on the b2i page #1543

**Which issue(s) this PR fixes**:
Fixes  #1543

**Special notes for reviewers:**
```
```
**Additional documentation, usage docs, etc.:**
```
```
/assign @xuliwenwenwen

2021-05-14 02:23 UTC, xuliwenwenwen commented
/lgtm

2021-05-14 08:16 UTC, TinaSprunt commented
/assign @harrisonliu5

2021-05-14 08:57 UTC, harrisonliu5 requested changes

2021-05-14 08:57 UTC, harrisonliu5 commented on src/pages/projects/containers/ImageBuilder/Detail/index.jsx
> +      text: t('run'),
There is no 'run' in locales language, only have the 'Run'.

2021-05-17 01:57 UTC, TinaSprunt commented on src/pages/projects/containers/ImageBuilder/Detail/index.jsx
> +      text: t('run'),
thanks，I got it

2021-05-17 03:13 UTC, TinaSprunt commented
/ assign @xuliwenwenwen
/assign @harrisonliu5

2021-05-17 03:48 UTC, xuliwenwenwen commented
/lgtm

2021-05-17 04:46 UTC, harrisonliu5 commented
/approve

2021-05-17 04:46 UTC, merged

2021-06-21 06:27 UTC, harrisonliu5 commented
/cherrypick release-3.1

2021-06-21 06:32 UTC, LinuxSuRen commented
/area devops