fix: Remove the console error
kubesphere/console pull request #1913
Opened 2021-05-20 08:31 UTC by fuchunlan

Signed-off-by: lannyfu <lannyfu@yunify.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes ##1903

**Special notes for reviewers**:
```
```

**Additional documentation, usage docs, etc.**:

https://user-images.githubusercontent.com/63338728/118946032-9b78ad00-b988-11eb-83a8-1020660c4299.mov

```docs

```

2021-05-20 10:10 UTC, JohnNiang requested changes

2021-05-20 10:10 UTC, JohnNiang commented on src/actions/configmap.js
> +            Notify.success({ content: `${t('Created Successfully')}` })
Actually, notification message should be `Updated Successfully` instead of `Created Successfully`.

2021-05-21 01:51 UTC, JohnNiang commented
/lgtm

2021-05-23 13:08 UTC, harrisonliu5 commented
/approve

2021-05-23 13:09 UTC, merged

2021-05-23 15:22 UTC, LinuxSuRen commented
hi @fuchunlan So glad to see your contribution to this project. But I found a very small detail about your contribution that you might not notice it before. As you can see from the following screenshot, it might be difficult for others to know who you are and what did you do due to the mismatch between your email `lannyfu@yunify.com` and your GitHub email setting. If you want to fix it, please visit [this page](https://github.com/settings/emails).

![image](https://user-images.githubusercontent.com/1450685/119266412-4c977580-bc1d-11eb-9d24-b318e204395b.png)

2021-05-24 13:28 UTC, fuchunlan commented
Thank you for reminding me.I have added a new email.@LinuxSuRen

2021-06-21 06:36 UTC, harrisonliu5 commented
/cherrypick release-3.1