Change Run Count to Run ID.
kubesphere/console pull request #2627
Opened 2021-11-22 06:18 UTC by Patrick-LuoYu

Signed-off-by: Patrick-LuoYu patrickluo@yunify.com

What type of PR is this?
/kind documentation

What this PR does / why we need it:
Change Run Count to Run ID.

Which issue(s) this PR fixes:
Fixes ## [2559](https://github.com/kubesphere/console/pull/2559#pullrequestreview-810734042)

Special notes for reviewers:
/assign @harrisonliu5 @JohnNiang  Please take a look. Thanks!

Does this PR introduced a user-facing change?
None

2021-11-22 06:21 UTC, JohnNiang requested changes
/cc @kubesphere/sig-devops

2021-11-22 06:21 UTC, JohnNiang commented on locales/tc/pipeline.js
> +  RUN_ID: 'Run ID',
IMO, here should be `運行 ID`.

2021-11-22 06:43 UTC, Patrick-LuoYu commented on locales/tc/pipeline.js
> +  RUN_ID: 'Run ID',
Traditional Chinese text should be handled by contributors from the community, because this is not a simple character conversion issue.

2021-11-22 06:45 UTC, Patrick-LuoYu commented on locales/tc/pipeline.js
> +  RUN_ID: 'Run ID',
FYI, https://zh.m.wikibooks.org/zh-hans/%E5%A4%A7%E9%99%86%E5%8F%B0%E6%B9%BE%E8%AE%A1%E7%AE%97%E6%9C%BA%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7%E8%A1%A8

2021-11-22 07:15 UTC, JohnNiang commented on locales/tc/pipeline.js
> +  RUN_ID: 'Run ID',
Fair enough.

2021-11-22 07:16 UTC, JohnNiang approved these changes
/lgtm

2021-11-23 02:36 UTC, xuliwenwenwen commented
/lgtm

2021-11-23 02:37 UTC, LinuxSuRen reviewed
/area devops
/lgtm

2021-11-23 02:41 UTC, harrisonliu5 commented
/approve

2021-11-23 02:41 UTC, harrisonliu5 commented
/cherrypick release-3.2

2021-11-23 02:43 UTC, merged