Fix: Certificate verification problem
kubesphere/console pull request #2705
Opened 2021-12-01 07:17 UTC by mangoGoForward

Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
Please see #2696. 
When verify credential, only display the type is equip to `username_password` 

### Which issue(s) this PR fixes:

Fixes #2696

### Does this PR introduced a user-facing change?

```release-note
None
```

2021-12-01 09:59 UTC, JohnNiang commented
/cc @kubesphere/sig-devops

2021-12-01 10:00 UTC, harrisonliu5 commented
/assign @xuliwenwenwen

2021-12-01 10:02 UTC, JohnNiang requested changes

2021-12-01 10:02 UTC, JohnNiang commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .filter(credential => credential.type === 'username_password'),
IMO, the type of credential should be `credential.devops.kubesphere.io/basic-auth` instead of `username_password`. Please see:

![image](https://user-images.githubusercontent.com/16865714/144213801-440899a3-40c9-4c85-837c-128f0d5f07d6.png)

2021-12-01 10:05 UTC, JohnNiang commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .filter(credential => credential.type === 'username_password'),
If I missed something, please feel free to correct me.

2021-12-01 10:17 UTC, JohnNiang approved these changes
/lgtm

I confirm that this PR fixes that issue very well.

![image](https://user-images.githubusercontent.com/16865714/144216209-582ed5f9-890b-4f42-a448-85b1d796063a.png)
![image](https://user-images.githubusercontent.com/16865714/144216261-d5913950-c305-4059-879b-1b7172c80ab4.png)

2021-12-01 10:17 UTC, JohnNiang commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .filter(credential => credential.type === 'username_password'),
I found that the credential list is transformed by:

https://github.com/kubesphere/console/blob/cf09f369c727dada8d12db2ca3b901c48fdb4a7a/src/stores/devops/credential.js#L94-L97

My bad! You are right.

2021-12-01 10:18 UTC, xuliwenwenwen commented
/lgtm

2021-12-01 10:21 UTC, JohnNiang commented
/cherry-pick release-3.2

2021-12-01 12:01 UTC, mangoGoForward commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .filter(credential => credential.type === 'username_password'),
Yes, the data was transformed.

2021-12-02 02:28 UTC, harrisonliu5 commented
/approve

2021-12-02 02:29 UTC, merged