fix: Update gateway setting conflect
kubesphere/console pull request #2758
Opened 2021-12-06 07:38 UTC by weili520

Signed-off-by: TheYoungManLi <cjl@kubesphere.io>

### What type of PR is this?
/kind bug

### What this PR does / why we need it:

### Which issue(s) this PR fixes:
Fixes ##2723

### Special notes for reviewers:

https://user-images.githubusercontent.com/33231138/144806181-4d621a56-902f-47cd-9801-9fd77fafc7fc.mov

### Does this PR introduced a user-facing change?
```release-note
NONE
```

### Additional documentation, usage docs, etc.:

2021-12-06 07:38 UTC, weili520 commented
/hold

2021-12-06 08:23 UTC, weili520 commented
/unhold

2021-12-07 02:42 UTC, Felixnoo requested changes
Hi, please see my comment. Thanks.

2021-12-07 02:42 UTC, Felixnoo commented on locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
> +  GATEWAY_UPDATING_TIP: 'Gateway is updating, please try again later.',
`Gateway is updating, please try again later.` -> `Updating the gateway. Please try again later.`

2021-12-07 02:45 UTC, weili520 commented on locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
> +  GATEWAY_UPDATING_TIP: 'Gateway is updating, please try again later.',
ok, thanks

2021-12-07 03:59 UTC, harrisonliu5 commented
/assign @xuliwenwenwen

2021-12-07 03:59 UTC, harrisonliu5 commented
/approve

2021-12-07 06:20 UTC, xuliwenwenwen commented
/lgtm

2021-12-07 06:21 UTC, merged

2021-12-07 06:46 UTC, harrisonliu5 commented
/cherry-pick release-3.2