fix: Add environment variables validation and tips
kubesphere/console pull request #2843
Opened 2021-12-13 09:04 UTC by weili520

Signed-off-by: TheYoungManLi <cjl@kubesphere.io>

### What type of PR is this?
/kind bug

### What this PR does / why we need it:

### Which issue(s) this PR fixes:
Fixes ##2790

### Special notes for reviewers:

https://user-images.githubusercontent.com/33231138/145782752-9c95a20a-d5b8-4901-adb6-46fbd256a86e.mov

### Does this PR introduced a user-facing change?
```release-note
NONE
```

### Additional documentation, usage docs, etc.:

2021-12-13 09:40 UTC, zryfish commented
/test pull-console-unit-test

2021-12-13 09:44 UTC, weili520 commented
/hold

2021-12-14 02:18 UTC, weili520 commented
/unhold

2021-12-14 02:44 UTC, zryfish commented
I think this PR does introduce a user-facing change, so a release note is required, also /cc @kubesphere/sig-docs , please help review the documentation.

2021-12-14 02:53 UTC, weili520 commented
> I think this PR does introduce a user-facing change, so a release note is required, also /cc @kubesphere/sig-docs , please help review the documentation.

2021-12-14 02:53 UTC, weili520 commented
/cc @kubesphere/sig-docs

2021-12-14 03:33 UTC, Felixnoo requested changes
Please see my comments, thanks.
/cc @Patrick-LuoYu

2021-12-14 03:33 UTC, Felixnoo commented on locales/en/l10n-projects-applicationWorkloads-deployments-list.js
> +    "A valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit.",
`A valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit.`
->
`The key of an environment variable can contain only letters, numbers, underscores (_), hyphens (-), and periods (.), and must not start with a number.`

2021-12-14 03:33 UTC, Felixnoo commented on locales/en/l10n-projects-applicationWorkloads-deployments-list.js
> +  ENVIRONMENT_CANNOT_BE_EMPTY: "Environment variable's key cannot be empty.",
`Environment variable's key cannot be empty.`
->
`Please set a key for the environment variable.`

2021-12-14 03:41 UTC, Patrick-LuoYu commented
/lgtm

2021-12-14 03:44 UTC, weili520 commented on locales/en/l10n-projects-applicationWorkloads-deployments-list.js
> +  ENVIRONMENT_CANNOT_BE_EMPTY: "Environment variable's key cannot be empty.",
Thanks.

2021-12-15 02:32 UTC, weili520 commented
/hold

2021-12-15 02:32 UTC, weili520 commented
> /hold

I need to change the error tip style.

2021-12-15 07:08 UTC, weili520 commented
/unhold

2021-12-15 07:08 UTC, weili520 commented
/test pull-console-unit-test

2021-12-16 03:19 UTC, harrisonliu5 commented
/assign @xuliwenwenwen

2021-12-16 03:25 UTC, xuliwenwenwen commented
/lgtm

2021-12-20 02:37 UTC, harrisonliu5 commented
/approve

2021-12-20 02:38 UTC, merged