feat: Avoid use the secret value in the DevOps scm verify API.
kubesphere/console pull request #2943
Opened 2022-02-16 10:48 UTC by mangoGoForward

Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What type of PR is this?

/kind feature

### What this PR does / why we need it:
Please see #2893

### Which issue(s) this PR fixes:

Fixes #2893

### Special notes for reviewers:
The request Payload screenshot like below:

![image](https://user-images.githubusercontent.com/35127166/154249058-fe6907d7-7714-4e29-aded-d16442f1a324.png)

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

2022-02-16 10:51 UTC, mangoGoForward commented
/area devops
/cc @kubesphere/sig-console

2022-02-16 10:52 UTC, mangoGoForward commented
/cc @kubesphere/sig-devops

2022-02-17 06:09 UTC, LinuxSuRen requested changes
hi @mangoGoForward thanks for your time. I'm sorry that I didn't update the description in time. But the new API was `/v1alpha3/scms/github/verify`

See the details from https://github.com/kubesphere/ks-devops/pull/439

2022-02-17 07:27 UTC, mangoGoForward commented
> hi @mangoGoForward thanks for your time. I'm sorry that I didn't update the description in time. But the new API was `/v1alpha3/scms/github/verify`
> 
> See the details from [kubesphere/ks-devops#439](https://github.com/kubesphere/ks-devops/pull/439)
> 
> The old API does not support it yet. See the following screenshot:
> 
> ![image](https://user-images.githubusercontent.com/1450685/154416039-13ccb684-594e-4dce-a245-0469cb5b3cfc.png)

I noticed that the API of `/v1alpha3/scms/github/verify` has two query parameters,

https://github.com/kubesphere/ks-devops/blob/d54a80ebd16c0df7b4698869babb17e41fec681e/pkg/kapis/devops/v1alpha3/register.go#L214-L215.

please correct me, there are two things:
1. update API version.
2. add this two parameters instead of `accessToken`.

But I'm confused that the API why would throw the error of `accessToken is required`?

2022-02-17 07:30 UTC, LinuxSuRen commented
You got the right way.

The old API does not accept the parameter `name`. This is the reason why it will throw the error.

2022-02-17 08:17 UTC, mangoGoForward commented
> ` [1ac41c4](/kubesphere/console/pull/2943/commits/1ac41c45c23a4aa21f57d3cf9ea0a55be5a8f7e8)`

Updated, please see 1ac41c4.

2022-02-17 08:26 UTC, LinuxSuRen commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .putAccessName({ secretName, secretNamespace, name, cluster, devops })
do we still need the parameter `name`?

2022-02-17 08:53 UTC, mangoGoForward commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .putAccessName({ secretName, secretNamespace, name, cluster, devops })
Not need, and the `putAccessName ` function would not receive `name` parameter.

2022-02-17 08:59 UTC, LinuxSuRen commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .putAccessName({ secretName, secretNamespace, name, cluster, devops })
How about just keeping the necessary parameters?

2022-02-17 09:11 UTC, mangoGoForward commented on src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
> +        .putAccessName({ secretName, secretNamespace, name, cluster, devops })
Done.

2022-02-23 10:15 UTC, LinuxSuRen requested changes
I got some problems when I test this PR manually.

![image](https://user-images.githubusercontent.com/1450685/155298850-755ba9fb-b628-4c83-9bff-5953086b9e8e.png)

![image](https://user-images.githubusercontent.com/1450685/155299695-efc694e9-ba1c-49b2-b405-6b067d93dfed.png)

Sorry about I didn't provide clear information about the API. See https://github.com/kubesphere/ks-devops/pull/439

The API takes `secret` and `secretNamespace` as the query parameters instead of payload.

The second problem is that I didn't get any tips when there is an error code. It will make users feel confused.

Sorry again for the inconvenience. I'll try to fix it based on your PR.

2022-02-24 10:19 UTC, mangoGoForward commented
> The API takes `secret` and `secretNamespace` as the query parameters instead of payload.

Sorry, I have not noticed that the use query parameters instead of payload, but the API method is `POST`,  may use query body better.

> The second problem is that I didn't get any tips when there is an error code. It will make users feel confused.

I will check.

2022-03-07 05:31 UTC, LinuxSuRen commented
I found out the front-end still call the following API which expose the password

![image](https://user-images.githubusercontent.com/1450685/156973783-820af5a9-1ef4-41a3-a228-bee7826e2d91.png)

2022-03-07 05:43 UTC, mangoGoForward commented
> I found out the front-end still call the following API which expose the password
> 
> ![image](https://user-images.githubusercontent.com/1450685/156973783-820af5a9-1ef4-41a3-a228-bee7826e2d91.png)

Seems can hide in this API, we use `scmType`, secret name and namespaces to instead of `data.password` now.

2022-03-07 05:45 UTC, LinuxSuRen commented
> Seems can hide in this API, we use scmType, secret name and namespaces to instead of data.password now.

It would be better.

2022-03-17 07:13 UTC, LinuxSuRen commented
Give the upstream project [go-scm](https://github.com/drone/go-scm) does not support listing repositories from a user or organization for now. I guess this PR needs to be held.

/hold

2022-03-29 01:55 UTC, LinuxSuRen commented
Please feel free to use the following image if you want to help to test this PR:
```
surenpi/ks-console:latest@sha256:449d6ffacf2ab3a9984b106cb93c028e152ca6ab508e6a6f1039167e6264b5ef
```

2022-03-30 05:40 UTC, LinuxSuRen approved these changes
I have tested it manually. It works well with [the last commit](https://github.com/kubesphere/console/pull/2943/commits/dc9e8851b8cc433575fd893f9bb65a95753aa2c5). See the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/160759182-ffe1a13f-ca13-4bb4-9393-701e03a84364.png)

/lgtm
/approve

2022-03-30 06:14 UTC, LinuxSuRen commented
/unhold

2022-03-31 02:22 UTC, harrisonliu5 commented
/approve

2022-03-31 02:22 UTC, merged