feat: Add Event tabs in pipeline run record
kubesphere/console pull request #3012
Opened 2022-03-24 07:47 UTC by harrisonliu5

Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>

### What type of PR is this?

/kind feature

### What this PR does / why we need it:

### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/console/issues/3003

### Special notes for reviewers:

![image](https://user-images.githubusercontent.com/17872673/159867395-1245db77-2e55-4637-b8d4-81c4443894d6.png)

### Does this PR introduced a user-facing change?

```release-note
feat: Add Event tabs in pipeline run record
```

### Additional documentation, usage docs, etc.:

```docs

```

2022-03-24 07:47 UTC, harrisonliu5 commented
/area devops

2022-03-24 08:44 UTC, JohnNiang commented
/cc @kubesphere/sig-devops

2022-03-24 08:46 UTC, LinuxSuRen requested changes

2022-03-24 08:46 UTC, LinuxSuRen commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> + * Copyright (C) 2019 The KubeSphere Console Authors.
`2019` or `2022`?

2022-03-24 08:46 UTC, LinuxSuRen commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> + * This file is part of KubeSphere Console.
why this is part of?

2022-03-24 08:52 UTC, JohnNiang requested changes
All code are good to me, but those lines. I have verified the changes work as same as before.

2022-03-24 08:52 UTC, JohnNiang commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> +      'involvedObject.uid': get(_originData, 'metadata.uid', ''),
```suggestion
      'involvedObject.name': _originData.metadata.name,
      'involvedObject.namespace': _originData.metadata.namespace,
      'involvedObject.kind': _originData.kind,
      'involvedObject.uid': _originData.metadata.uid,
```

2022-03-24 08:56 UTC, JohnNiang commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> +      namespace: devops,
```suggestion
      namespace: _originData.metadata.namespace,
```

2022-03-24 09:59 UTC, harrisonliu5 commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> + * Copyright (C) 2019 The KubeSphere Console Authors.
This is a general description

2022-03-24 09:59 UTC, harrisonliu5 commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> + * This file is part of KubeSphere Console.
This is a general description

2022-03-24 10:05 UTC, harrisonliu5 commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> +      'involvedObject.uid': get(_originData, 'metadata.uid', ''),
maybe the `originData` is empty, so need the `get` function to init the data. @JohnNiang

2022-03-24 10:11 UTC, harrisonliu5 commented
@JohnNiang @LinuxSuRen  please review again, thaks

2022-03-25 01:08 UTC, LinuxSuRen commented on src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
> + * Copyright (C) 2019 The KubeSphere Console Authors.
`The year in the copyright notice refers to the year of first publication`

See also https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work

but I don't block anyone to merge this PR.

2022-03-25 01:13 UTC, LinuxSuRen commented
In case of anyone might want to use image to test this PR, I post the image following:

```
surenpi/ks-console:latest@sha256:1066563c09d6c75b17b0e848c9c9c76e0eabe23c0cf02a1b1f7af29f37f9267e
```

2022-03-25 01:33 UTC, LinuxSuRen requested changes
It does not work well if I directly visit this page instead of switching to it.

![image](https://user-images.githubusercontent.com/1450685/160037190-459da5ba-1bf1-4698-bc7d-44921356f935.png)

2022-03-25 08:06 UTC, JohnNiang approved these changes
I can confirm that the issue mentioned https://github.com/kubesphere/console/pull/3012#pullrequestreview-921087873 has been fixed by the latest commits.

![image](https://user-images.githubusercontent.com/16865714/160079854-570940a3-7258-42d4-bbb0-f64c414692d7.png)

/lgtm

2022-03-25 08:06 UTC, merged