Update UI text of 'Continuous Deployments'
kubesphere/console pull request #3066
Opened 2022-04-08 10:06 UTC by Patrick-LuoYu

Signed-off-by: Patrick-LuoYu patrickluo@yunify.com

## What type of PR is this?
/kind documentation

## What this PR does / why we need it:
Update UI text of 'Continuous Deployments'.

## Special notes for reviewers:
/assign @harrisonliu5 @LinuxSuRen 

## Does this PR introduced a user-facing change?
```release-note
None
```

2022-04-08 10:08 UTC, LinuxSuRen commented
/area devops
/cc @kubesphere/sig-devops

2022-04-08 11:15 UTC, LinuxSuRen requested changes
Missing something?

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1450685/162425101-620fbfa3-f359-4740-82e2-5e4134f2c444.png">

2022-04-08 11:15 UTC, LinuxSuRen commented on locales/en/l10n-devopsProjects-codeRepo-list.js
> +  CODE_REPO_DESC: 'Manage code repositories based on Git or SVN.',
We don't support SVN here.

2022-04-08 11:15 UTC, LinuxSuRen commented on locales/en/l10n-devopsProjects-codeRepo-list.js
> +    'Import a code repository from GitHub, GitLab, or Bitbucket. You can also use Git or SVN to directly pull source code.',
We don't support SVN here.

2022-04-11 01:46 UTC, Patrick-LuoYu commented
Fixed

2022-04-11 01:57 UTC, harrisonliu5 commented
/test pull-console-unit-test

2022-04-11 01:58 UTC, Patrick-LuoYu commented
@LinuxSuRen @harrisonliu5 Please take a look. Thanks.

2022-04-11 02:06 UTC, LinuxSuRen commented
> Fixed

I need to review all the files again considering you push the commit changes with the flag `--force`. I highly recommend don't use the flag `--force` often. If you'd like to know more recommendations about it, please feel free to read [here](https://github.com/LinuxSuRen/open-source-best-practice/blob/master/how-to-contribute.md).

2022-04-11 02:37 UTC, Patrick-LuoYu commented
> > Fixed
> 
> I need to review all the files again considering you push the commit changes with the flag `--force`. I highly recommend don't use the flag `--force` often. If you'd like to know more recommendations about it, please feel free to read [here](https://github.com/LinuxSuRen/open-source-best-practice/blob/master/how-to-contribute.md).
> 
> I'm doing the test with the following image:
> 
> ```
> surenpi/ks-console:latest@sha256:1c6e0e0f3a89b4b7ad74f63c5a2472fb3fac3dd9d167068b8f0c4e3f9cdb334e
> ```

I personally prefer keeping all commit records of a PR. However, I was asked by the previous administrator of this repo to merge all commits in a PR into one commit. @LinuxSuRen Please confirm with @harrisonliu5 whether we should merge commits of a PR, so that we can work based on a consistent protocol.

2022-04-11 02:52 UTC, LinuxSuRen reviewed
It looks great from the UI with the manual tests. But I didn't review all the files in this PR.
LGTM

2022-04-11 03:18 UTC, harrisonliu5 commented
/lgtm
/approve

2022-04-11 03:18 UTC, merged