fix: Optimize getting the value of the parameter from API
kubesphere/console pull request #3158
Opened 2022-04-19 06:52 UTC by harrisonliu5

Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>

### What type of PR is this?

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

2022-04-19 06:53 UTC, harrisonliu5 commented
/area devops
/cc @kubesphere/sig-devops

2022-04-19 07:43 UTC, LinuxSuRen commented
Please feel free to use the following image test it:
```
surenpi/ks-console:latest@sha256:3fb02707b0f4ac4902f837eacef2e5442fd689a5fe8db15e91b3ee4198c2c253
```

2022-04-20 02:36 UTC, LinuxSuRen requested changes
We need to fetch the parameter if `spec.pipeline.parameters` or `spec.pipeline.parametersFrom` is not empty.

![image](https://user-images.githubusercontent.com/1450685/164135641-b3dc3f82-153d-4e9c-88e3-62c570dcf024.png)

2022-04-20 02:36 UTC, LinuxSuRen commented on src/stores/devops/pipelines.js
> +          namespace: devops,
For this API, we need to use `devops` instead of `namespace`.

See `/devops/{devops}/pipelines/{pipeline}/parameters`

2022-04-20 11:28 UTC, lxm commented
<img width="889" alt="image" src="https://user-images.githubusercontent.com/1918195/164220700-dd380e65-9d79-4672-9652-822efb62eab9.png">

default_values did not list  @harrisonliu5

2022-04-20 11:39 UTC, lxm commented
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1918195/164222377-3f6b1d9b-4483-4432-aa02-28344cb449d3.png">
if parameters of the pipeline are empty,but parametersFrom is not empty, still need to prop  the param input dialog .

2022-04-22 00:51 UTC, LinuxSuRen commented
hi @harrisonliu5 , I'm so sorry about this PR. @lxm and I didn't expect this feature just does work. We are going to revert it from the backend. See details from [here](https://github.com/kubesphere/ks-devops/pull/560).

To make it short, I guess we need close this PR. Sorry for your time.

2022-04-22 02:08 UTC, closed without merging