optimization the image building of KubeSphere/console
kubesphere/console pull request #3591
Opened 2022-08-19 10:15 UTC by zt1046656665

Signed-off-by: zhoutian <zhoutian@yunify.com>

### What type of PR is this?

### What this PR does / why we need it:
we can build image easily by this PR

### Which issue(s) this PR fixes:

Fixes #optimization the image building of KubeSphere/console

### Special notes for reviewers:
```
optimization the image building of KubeSphere/console
```

### Does this PR introduced a user-facing change?

```release-note
first we build the pre-image to get the file by webpacking
then we can build the image of linux/amd64,linux/arm64  by copy the file
finally we will rmi the pre-image and rm the file by webpacking
```

### Additional documentation, usage docs, etc.:

```docs

```

2022-08-22 01:27 UTC, LinuxSuRen requested changes

2022-08-22 01:27 UTC, LinuxSuRen commented on build/Dockerfile.dapper
> +# Copyright 2021 The KubeSphere Authors. All rights reserved.
You just created this file. So, this year should be 2022 instead of 2021.

2022-08-22 04:42 UTC, zt1046656665 commented on build/Dockerfile.dapper
> +# Copyright 2021 The KubeSphere Authors. All rights reserved.
yes,it should be 2022,,thanks,i will correct this,

2022-08-25 06:43 UTC, pixiake commented
/cherry-pick release-3.3

2022-08-25 06:44 UTC, harrisonliu5 commented
/lgtm
/approve

2022-08-25 06:51 UTC, merged