fix:port name cant have consecutive hyphens
kubesphere/console pull request #3976
Opened 2022-11-14 09:44 UTC by zhaohuiweixiao

Signed-off-by: zhaohuihui <zhaohuihui_yewu@cmss.chinamobile.com>

### What type of PR is this?
/kind bug

### What this PR does / why we need it:
the port name can not have consecutive hyphens in k8s.
![portnameconsecutivepng](https://user-images.githubusercontent.com/6092586/201627328-0260778d-6c46-4fb5-8b26-88225d4d0c6f.png)

### Special notes for reviewers:
```
/assign harrisonliu5
```

### Does this PR introduced a user-facing change?
```release-note
fix: port name add consecutive hyphens validation
```

2022-11-15 09:05 UTC, zhaohuiweixiao commented
How can I verify that my expression is efficient offline? i test the regular express no problem on https://regex101.com/.
@harrisonliu5 @patrickluoyu

2022-11-22 09:46 UTC, harrisonliu5 commented
> This part of the regular expression may cause exponential backtracking on strings starting with 'a' and containing many repetitions of '0'.

you should resolve this error first.

2023-06-25 03:05 UTC, Bettygogo2021 requested changes

2023-06-25 03:05 UTC, Bettygogo2021 commented on locales/en/l10n-projects-applicationWorkloads-deployments-list.js
> +  WORKLOAD_PORT_NAME_DESC: 'The port name can contain only lowercase letters, numbers and hyphens (-), and must start with a lowercase letter and end with a lowercase letter or number, and cannot hav
The port name can contain only lowercase letters, numbers and hyphens (-), and must start with a lowercase letter and end with a lowercase letter or number. Avoid using consecutive hyphens. The maximum length is 15 characters.

2024-09-13 10:19 UTC, closed without merging