feat: Add devops pipeline custom pipeline modal locales
kubesphere/console pull request #4109
Opened 2023-04-14 08:22 UTC by yazhouio

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
feat: Add devops pipeline custom pipeline modal locales
### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/ks-devops/issues/609 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
feat: Add devops pipeline custom pipeline modal locales
```

### Additional documentation, usage docs, etc.:

```docs

```

2023-04-14 08:32 UTC, yazhouio commented
/assign @hongzhouzi

2023-04-17 03:36 UTC, harrisonliu5 commented
/assign @Bettygogo2021

2023-04-17 08:10 UTC, Bettygogo2021 requested changes

2023-04-17 08:10 UTC, Bettygogo2021 commented on locales/en/l10-project-devops-pipeline-detail.js
> +  'Keep Long Output': 'Keep Long Output',
Retain long output

2023-04-17 08:10 UTC, Bettygogo2021 commented on locales/en/l10-project-devops-pipeline-detail.js
> +  'Skip Publishing Checks': 'Skip Publishing Checks',
Skip publishing checks

2023-04-17 08:10 UTC, Bettygogo2021 commented on locales/en/l10-project-devops-pipeline-detail.js
> +  'Config Name': 'Config Name',
Configuration Item

2023-04-17 08:21 UTC, harrisonliu5 commented
/assign @yazhouio

2023-04-17 09:07 UTC, yazhouio commented on locales/en/l10-project-devops-pipeline-detail.js
> +  'AbortPipeline if quality gate status is not green':
The key is consistent with the value in YAML, so it will not be changed.

2023-04-17 09:10 UTC, Bettygogo2021 commented
/lgtm

2023-04-17 09:10 UTC, Bettygogo2021 commented
/lgtm

2023-04-17 10:01 UTC, merged