docs: Add the USE_IMAGE_DEFAULT_PORTS word
kubesphere/console pull request #4144
Opened 2023-06-21 07:45 UTC by harrisonliu5

### What type of PR is this?

/kind documentation

### What this PR does / why we need it:

### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

2023-06-21 07:45 UTC, harrisonliu5 commented
/assign @Bettygogo2021

2023-06-21 07:54 UTC, harrisonliu5 commented on locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
> +  USE_IMAGE_DEFAULT_PORTS: 'Use Image Default Ports',
only should review this word, thank @Bettygogo2021

2023-06-25 02:55 UTC, Bettygogo2021 requested changes

2023-06-25 02:55 UTC, Bettygogo2021 commented on locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
> +  USE_IMAGE_DEFAULT_PORTS: 'Use Image Default Ports',
Use Default Port of Images

2023-06-25 06:35 UTC, harrisonliu5 commented on locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
> +  USE_IMAGE_DEFAULT_PORTS: 'Use Image Default Ports',
done

2023-06-25 07:26 UTC, merged