feat: add devops locale
kubesphere/console pull request #4149
Opened 2023-06-21 10:48 UTC by yazhouio

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
feat: add devops locale
### Which issue(s) this PR fixes:

Fixes #https://github.com/kubesphere/issues/issues/1198
### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

2023-06-21 10:49 UTC, yazhouio commented
need pick to kse 3.4.1

2023-06-25 02:37 UTC, Bettygogo2021 requested changes
pls change the trans.

2023-06-25 02:37 UTC, Bettygogo2021 commented on locales/en/l10n-devopsProjects-pipeline-details.js
>    PIPELINE_CONFIGURATION: 'Pipeline Configuration',
Pipeline Configurations

2023-06-25 02:37 UTC, Bettygogo2021 commented on locales/en/l10n-devopsProjects-pipeline-details.js
> +  BRANCH_DISABLED_NOT_REPLAY: 'The branch is disabled and cannot be replayed.',
The branch has been disabled and cannot be replayed.

2023-06-25 06:37 UTC, harrisonliu5 commented
@yazhouio need to update

2023-06-25 06:50 UTC, Bettygogo2021 commented
/lgtm

2023-06-25 07:05 UTC, harrisonliu5 commented
/approve

2023-06-25 07:16 UTC, merged